version: "3"

services:
  mosquitto:
    image: eclipse-mosquitto:2.0.18
    restart: ${RESTART_POLICY}
      # network_mode: host
    ports:
      - 1883:1883
    volumes:
      - ${MQTT_CONF_DIR}:/mosquitto/config
      - ${MQTT_DATA_DIR}:/mosquitto/data
      - ${MQTT_LOG_DIR}:/mosquitto/log
