version: "2.1"

services:
  mariadb:
    image: linuxserver/mariadb:10.11.5
    container_name: mariadb
    restart: ${RESTART_POLICY}
    networks:
      - proxy
    volumes:
      - ${MARIADB_CONF_DIR}:/config
      - ${MARIADB_DATA_DIR}:/var/lib/mysql
    ports:
      - ${MARIADB_PORT}:3306

networks:
  proxy:
    external: true
