services:
  kopia:
    image: kopia/kopia:${KOPIA_VER}
    container_name: Kopia
    user: "0:0"
    restart: ${RESTART_POLICY}
    networks:
      - proxy
    privileged: true
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    devices:
      - /dev/fuse:/dev/fuse:rwm
    command:
      - server
      - start
      - --insecure
      - --disable-csrf-token-checks
      - --address=0.0.0.0:${KOPIA_PORT}
      - --server-username=${KOPIA_USER}
      - --server-password=${KOPIA_PASSWORD}
    volumes:
      - ${KOPIA_MNT}:/tmp:shared # mount drives here
      - ${KOPIA_CONFIG}:/app/config
      - ${KOPIA_CACHE}:/app/cache
      - ${KOPIA_LOGS}:/app/logs
      - ${DOCKER_DATA_DIR}:/data:ro
      - ${KOPIA_BACKUPS}:/backups
    environment:
      KOPIA_PASSWORD: ${KOPIA_LOCAL_PASSWORD}
      USER: ${KOPIA_USER}
      TZ: ${TZ}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kopia.entrypoints=http"
      - "traefik.http.routers.kopia.rule=Host(`${KOPIA_URL}`)"
      - "traefik.http.middlewares.kopia-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.kopia.middlewares=kopia-https-redirect"
      - "traefik.http.routers.kopia-secure.entrypoints=https"
      - "traefik.http.routers.kopia-secure.rule=Host(`${KOPIA_URL}`)"
      - "traefik.http.routers.kopia-secure.tls=true"
      - "traefik.http.routers.kopia-secure.service=kopia"
      - "traefik.http.services.kopia.loadbalancer.server.port=51515"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true

### From Kopia repo: https://github.com/kopia/kopia/blob/master/tools/docker/docker-compose.yml
        
### IF you would like to assign hostname and domain name to your server.       
#      hostname: "XXX"
#      domainname: "XXX"

### If you want to assign ip to your container with an existing Docker Network.
### Existing networks name is "Docker" in below example. Just change it with your own.
#      networks:
#        Docker:
#          ipv4_address: aaa.bbb.ccc.ddd

#### If you would like to assign DNS Server
#      dns:
#        - 8.8.8.8
#
