version: "2.1"
services:
  syncthing:
    image: linuxserver/syncthing:1.27.2
    container_name: syncthing
    restart: ${RESTART_POLICY}
    hostname: Raspberry Pi #optional
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    environment:
      - PUID=${SYNCTHING_PUID}
      - PGID=${SYNCTHING_PGID}
    volumes:
      - ${SYNCTHING_CONF_DIR}:/config
      - ${SYNCTHING_DATA1_DIR}:/data1
      - ${SYNCTHING_DATA2_DIR}:/data2
    ports:
      - 8384:8384
      - 22000:22000
      - 21027:21027/udp
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.syncthing.entrypoints=http"
      - "traefik.http.routers.syncthing.rule=Host(`${SYNCTHING_URL}`)"
      - "traefik.http.middlewares.syncthing-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.syncthing.middlewares=syncthing-https-redirect"
      - "traefik.http.routers.syncthing-secure.entrypoints=https"
      - "traefik.http.routers.syncthing-secure.rule=Host(`${SYNCTHING_URL}`)"
      - "traefik.http.routers.syncthing-secure.tls=true"
      - "traefik.http.routers.syncthing-secure.service=syncthing"
      - "traefik.http.services.syncthing.loadbalancer.server.port=8384"
        #- "traefik.http.services.syncthing.loadbalancer_sync.server.port=22000"
        #- "traefik.http.services.syncthing.loadbalancer_sync_udp.server.port=21027/udp"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true
